### ISSUE TITLE
Create a header on main page using bootstrap

### ISSUE THREAD

**Issue by ghousahmed367** [ghousahmed367/e-commerce-store#1]

**Comment by Shahmeerhussain1** [comment]
Please Assign it to me

**Comment by Shahmeerhussain1** [comment]
Assign it to me

**Comment by akhilender-bongirwar** [comment]
Hi @ghousahmed367, can you assign it to me?

**Comment by sadiqshah786** [comment]
Please Assign  me to the this project I can do it best

**Comment by mdhasnainhanif** [comment]
please assign it to me

**Comment by ghousahmed367** [comment]
> Please Assign me to the this project I can do it best

Please start working

**Comment by Stargnite** [comment]
Kindly assign this to me, I can work on it
